# Generated by Django 3.2.4 on 2022-11-28 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0006_masterlookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtRegistration',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_patient', models.CharField(max_length=50)),
                ('date_registration', models.DateField()),
                ('pre_art_no', models.CharField(max_length=50)),
                ('status_in_pre_art_care', models.PositiveIntegerField(choices=[(1, 'Eligible but not Initiated on ART'), (2, 'Died'), (3, 'Opted out'), (4, 'Transfer Out'), (5, 'Initiated on ART'), (6, 'LFU before 31 Dec 2016'), (7, 'LFU after 1 Jan 2017')])),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_cause_uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('death_reason', models.TextField(blank=True, null=True)),
                ('transferred_in', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('transfer_in_status', models.PositiveIntegerField(blank=True, choices=[(1, 'PRE ART'), (2, 'On ART')], null=True)),
                ('date_art_initiation', models.DateField(blank=True, null=True)),
                ('private_treatment_history', models.PositiveIntegerField(choices=[(1, 'NO'), (2, 'YES'), (3, 'Update')])),
                ('art_initiation_private_date', models.DateField(blank=True, null=True)),
                ('hiv_test_confirmed_date', models.DateField()),
                ('ictc_code', models.CharField(max_length=50)),
                ('pid_number', models.CharField(max_length=70, unique=True)),
                ('hiv_report', models.PositiveIntegerField(choices=[(1, 'HIV-1'), (2, 'HIV-2'), (3, 'HIV-1 & 2'), (4, 'Update')])),
                ('art_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('art_start_date', models.DateField(blank=True, null=True)),
                ('art_care_status', models.PositiveIntegerField(blank=True, choices=[(1, 'Alive on ART'), (2, 'Died'), (3, 'LFU after 1 Jan 2017'), (4, 'Stopped'), (5, 'MIS'), (6, 'Transfer Out'), (7, 'Opted out'), (8, 'LFU before 31 Dec 2016')], null=True)),
                ('already_diagnosed_tb', models.PositiveIntegerField(choices=[(1, 'NO'), (2, 'YES'), (3, 'Update')])),
                ('nikshay_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('samvaad_application_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('transfer_out_confirmation_data', models.DateField(blank=True, null=True)),
                ('transferred_art_code', models.CharField(blank=True, max_length=100, null=True)),
                ('disclosure_with_family', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES'), (3, 'Update')], null=True)),
                ('art_family_id', models.CharField(blank=True, max_length=250, null=True)),
                ('imported', models.BooleanField(default=False)),
                ('art_reg_diabetes', models.PositiveIntegerField(blank=True, choices=[(1, 'Pre-existing'), (2, 'Detected during treatment'), (3, 'No')], null=True)),
                ('art_reg_hypertention', models.PositiveIntegerField(blank=True, choices=[(1, 'Pre-existing'), (2, 'Detected during treatment'), (3, 'No')], null=True)),
                ('art_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_center', to='master_data.boundary')),
                ('transferred_in_from_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.boundary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
