# Generated by Django 3.2.4 on 2022-11-29 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0006_masterlookup'),
        ('patientmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTPatientLinkage',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Transferred in'), (2, 'Transferred out')])),
                ('art_center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_center_art_link', to='master_data.boundary')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='patientmanagement.artregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
