# Generated by Django 3.2.4 on 2022-11-29 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientmanagement', '0002_artpatientlinkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('present_status_in_pre_art_care', models.PositiveIntegerField(blank=True, choices=[(1, 'Eligible but not Initiated on ART'), (2, 'Died'), (3, 'Opted out'), (4, 'Transfer Out'), (5, 'Initiated on ART'), (6, 'LFU before 31 Dec 2016'), (7, 'LFU after 1 Jan 2017')], null=True)),
                ('past_status_in_pre_art_care', models.PositiveIntegerField(blank=True, choices=[(1, 'Eligible but not Initiated on ART'), (2, 'Died'), (3, 'Opted out'), (4, 'Transfer Out'), (5, 'Initiated on ART'), (6, 'LFU before 31 Dec 2016'), (7, 'LFU after 1 Jan 2017')], null=True)),
                ('present_status_art_care', models.PositiveIntegerField(blank=True, choices=[(1, 'Alive on ART'), (2, 'Died'), (3, 'LFU after 1 Jan 2017'), (4, 'Stopped'), (5, 'MIS'), (6, 'Transfer Out'), (7, 'Opted out'), (8, 'LFU before 31 Dec 2016')], null=True)),
                ('past_status_art_care', models.PositiveIntegerField(blank=True, choices=[(1, 'Alive on ART'), (2, 'Died'), (3, 'LFU after 1 Jan 2017'), (4, 'Stopped'), (5, 'MIS'), (6, 'Transfer Out'), (7, 'Opted out'), (8, 'LFU before 31 Dec 2016')], null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_name', to='patientmanagement.artregistration')),
            ],
            options={
                'verbose_name_plural': 'Status History',
            },
        ),
    ]
