# Generated by Django 3.2.4 on 2022-11-29 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientmanagement', '0004_anyio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTVisit',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_visit', models.DateField()),
                ('plha_visit_status', models.PositiveIntegerField(choices=[(1, 'Self'), (2, 'Proxy'), (3, 'Virtual')])),
                ('pills_remaining', models.IntegerField(default=0)),
                ('pills_prescribed_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pills_prescribed_last_visit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cda_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('cda4_count', models.IntegerField(blank=True, null=True, verbose_name='CD4_count')),
                ('viral_load_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('viral_load_reason', models.PositiveIntegerField(blank=True, choices=[(1, 'General / Routine'), (2, 'Suspected Failuer'), (3, '2nd or 3rd Line Regimen Follow-up'), (4, 'Pregnant & Breastfeeding Women'), (5, 'Repeate Test after EAC')], null=True)),
                ('viral_load_count', models.BigIntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('systolic', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('diastolic', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('screening_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('night_sweats', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('s4_screening_status', models.PositiveIntegerField(blank=True, choices=[(1, '4S +ve'), (2, '4S -ve')], null=True)),
                ('fever', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('cough', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('blood_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('blood_test_result_recieved', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fasting', models.IntegerField(blank=True, null=True)),
                ('post_prandial', models.IntegerField(blank=True, null=True)),
                ('random', models.IntegerField(blank=True, null=True)),
                ('serum_creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_cholestrol', models.IntegerField(blank=True, null=True)),
                ('liver_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('liver_test_recieved', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('sbilirubin', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sgot_ast', models.IntegerField(blank=True, null=True)),
                ('sgpt_alt', models.IntegerField(blank=True, null=True)),
                ('reactive_protein_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('reactive_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hbv_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('hcv_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('tb_lam_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('result_tb_lam_test', models.PositiveIntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Awaiting Result')], null=True)),
                ('craig_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('result_craig', models.PositiveIntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Awaiting Result')], null=True)),
                ('cryptococcal_menigitis_date', models.DateField(blank=True, null=True)),
                ('cryptococcal_meningitis_place', models.CharField(blank=True, max_length=250, null=True)),
                ('cryptococcal_meningitis_diagnosis', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('due_date_visit_artc', models.DateField(blank=True, null=True)),
                ('syphilis_test_conducted', models.PositiveIntegerField(blank=True, choices=[(1, 'NO'), (2, 'YES')], null=True)),
                ('indication_lam', models.PositiveIntegerField(blank=True, choices=[(1, '4S Symptom positive & CD4<200 cells/mm3'), (2, '4S Negative & CD4 <200 cells/mm3'), (3, 'WHO Stage III/IV Disease')], null=True)),
                ('who_staging', models.PositiveIntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], null=True)),
                ('pre_emptive_start_date', models.DateField(blank=True, null=True)),
                ('pre_emptive_therapy_completion_date', models.DateField(blank=True, null=True)),
                ('craig_indication', models.PositiveIntegerField(blank=True, choices=[(1, 'Symptoms of Meningitis & CD4 <200'), (2, 'Asymptomatic & CD4 <200'), (3, 'WHO Stage III/IV')], null=True)),
                ('adherance_percentage', models.IntegerField(blank=True, null=True)),
                ('results_added', models.BooleanField(default=False)),
                ('any_oi_uuid', models.ManyToManyField(blank=True, to='patientmanagement.AnyIo')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_art_visit', to='patientmanagement.artregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
