# Generated by Django 3.2.4 on 2022-11-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseContent',
        ),
    ]
