# Generated by Django 3.2.4 on 2022-11-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_sacepconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
